target:
  namespace: "bd"                                         # Black Duck namespace
  labelSelector: "app.kubernetes.io/instance=blackduck"   # Selector for Black Duck pods
  annotateWorkloads: true                                 # Annotate scanned workloads
  annotateKey: "blackduck.synopsys.com/policy"
  annotateValueOnPass: "pass"

blackduck:
  url: ""                              # Leave blank - pulled from secret
  token: ""                            # Leave blank - pulled from secret
  tokenSecretName: "blackduck-creds"   # Secret containing Black Duck credentials
  trustCert: true                      # Set to false if using proper SSL certs

detect:
  policyFailSeverities: "CRITICAL,BLOCKER"
  parentProject: ""                    # Optional: override parent project name
  parentVersion: ""                    # Optional: override parent version
  projectGroupName: ""                 # Optional: Black Duck project group/application ID
  projectTier: "3"                     # Project tier (1=Critical, 2=High, 3=Medium, 4=Low)

registry:
  secretName: ""                       # Optional: registry auth secret name

runner:
  image: "alpine:3.19"                 # MicroK8s-compatible base image for BDSC container scanning

# Docker Inspector configuration (if using standalone Docker Inspector)
dockerInspector:
  install: false                       # Set to true if you want dedicated Docker Inspector services
  replicas: 1
  image: "blackducksoftware/blackduck-imageinspector-ubuntu:6.2.1"
  createSharedPvc: false
  sharedPvcName: "bd-imageinspector-shared"
