target:
  namespace: "bd"                                         # Black Duck namespace
  labelSelector: "app=blackduck"                         # Scan Black Duck containers
  annotateWorkloads: true
  annotateKey: "blackduck.synopsys.com/policy"
  annotateValueOnPass: "pass"

blackduck:
  url: ""                              # Leave blank - pulled from secret
  token: ""                            # Leave blank - pulled from secret
  tokenSecretName: "blackduck-creds"   # Secret containing Black Duck credentials
  trustCert: true                      # Set to false if using proper SSL certs

detect:
  policyFailSeverities: "CRITICAL,BLOCKER"
  # CORRECTED: Use Project Group instead of parent project
  projectGroupName: "blackduck-platform-containers"      # Project Group name (created first)
  projectTier: "2"                     # Project tier (1=Critical, 2=High, 3=Medium, 4=Low)
  
  # Additional BDSC-specific settings
  containerScan:
    enabled: true                      # Enable container scanning
    waitForResults: true               # Wait for scan completion
    cleanupAfterScan: false           # Keep scan artifacts for debugging

registry:
  secretName: ""                       # Optional: registry auth secret name

runner:
  image: "alpine:3.19"                 # Base image for scanning container
  
  # Enhanced resource limits for the scanning job
  resources:
    requests:
      memory: "2Gi"                    # Increased from default
      cpu: "500m"
    limits:
      memory: "8Gi"                    # Increased for larger images
      cpu: "4"                         # More CPU for faster processing
      ephemeralStorage: "50Gi"         # Disk space for image downloads

# Enhanced logging and debugging
debug:
  enabled: false                       # Set to true for verbose debugging
  keepTempFiles: false                # Keep temporary files for debugging
  logLevel: "INFO"                    # DEBUG, INFO, WARN, ERROR

# Docker Inspector configuration (optional - for traditional Docker Inspector mode)
dockerInspector:
  install: false                       # Set to true if you want dedicated Docker Inspector services
  replicas: 1
  image: "blackducksoftware/blackduck-imageinspector-ubuntu:6.2.1"
  createSharedPvc: false
  sharedPvcName: "bd-imageinspector-shared"
