target:
  namespace: "bd"                                         # Black Duck namespace
  labelSelector: "app.kubernetes.io/instance=blackduck"   # Selector for Black Duck pods
  annotateWorkloads: true                                 # Annotate scanned workloads
  annotateKey: "blackduck.synopsys.com/policy"
  annotateValueOnPass: "pass"

blackduck:
  url: ""                              # Leave blank - pulled from secret
  token: ""                            # Leave blank - pulled from secret
  tokenSecretName: "blackduck-creds"   # Secret containing Black Duck credentials
  trustCert: true                      # Set to false if using proper SSL certs

detect:
  policyFailSeverities: "CRITICAL,BLOCKER"
  parentProject: ""                    # Optional: override parent project name
  parentVersion: ""                    # Optional: override parent version
  projectGroupName: ""                 # Optional: Black Duck project group

registry:
  secretName: ""                       # Optional: registry auth secret name

runner:
  image: "alpine:3.19"                 # Base image for scan job
