# BD SelfScan Configuration
# Global Configuration
global:
  namespace: bd-selfscan-system
  
# Black Duck Configuration  
blackduck:
  url: ""  # From secret
  token: ""  # From secret
  tokenSecretName: "blackduck-creds"
  trustCert: true

# Phase 1: On-demand scanning
onDemand:
  enabled: true

# Scanning target (can be set via --set scanTarget="Application Name")
# Leave empty to scan all configured applications
scanTarget: ""

# Phase 2: Automated scanning (disabled until Phase 1 validation complete)
automated:
  enabled: false  # Enable after Phase 1 validation
  controller:
    image: "python:3.11-alpine"
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi" 
        cpu: "500m"
  
  # Webhook for deployment events
  webhook:
    enabled: false
    port: 8443
    
  # Scheduled scanning
  scheduled:
    enabled: false

# Scanner pod configuration
scanner:
  image: "alpine:3.19"
  resources:
    requests:
      memory: "2Gi"
      cpu: "500m"
    limits:
      memory: "8Gi"
      cpu: "4"
      ephemeralStorage: "50Gi"

# Application configurations
# This will be loaded from the ConfigMap, but can be overridden here for testing
applications: []  # Loaded from bd-selfscan-applications ConfigMap

# Black Duck Detect Configuration
detect:
  # Default policy failure severities
  policyFailSeverities: "CRITICAL,BLOCKER"
  
  # Project organization settings
  parentProject: ""
  parentVersion: ""
  projectGroupName: ""
  projectTier: 3
  
  # Timeout and retry settings
  timeout: "1800"  # 30 minutes
  retries: "3"

# Registry Configuration (for private registries)
registry:
  secretName: ""  # Optional: Secret containing registry credentials

# Container Image Download Settings
containerDownload:
  timeout: "600"  # 10 minutes per image
  retries: "3"

# Monitoring and observability
monitoring:
  enabled: true
  serviceMonitor:
    enabled: false
    
# Debug settings
debug:
  enabled: false
  logLevel: "INFO"
  keepTempFiles: false

# Job TTL and cleanup
job:
  ttlSecondsAfterFinished: 3600  # 1 hour
  backoffLimit: 2

# Security context
securityContext:
  runAsNonRoot: false  # BDSC Container scanning requires specific permissions
  runAsUser: 1001
  runAsGroup: 1001
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL