{{- if and .Values.automated.enabled .Values.automated.scheduled.enabled }}
{{- $apps := (index .Values.applications) }}
{{- range $app := $apps }}
{{- if $app.scanSchedule }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "bd-selfscan.name" $ }}-{{ $app.name | lower | replace " " "-" }}
  namespace: {{ $.Values.global.namespace }}
spec:
  schedule: "{{ $app.scanSchedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "bd-selfscan.name" $ }}
          restartPolicy: Never
          containers:
            - name: scanner
              image: {{ $.Values.scanner.image }}
              command: ["/scripts/scan-application.sh"]
              args: ["{{ $app.name }}"]
              # ... (similar volume mounts and env vars as on-demand job)
{{- end }}
{{- end }}
{{- end }}