apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bd-selfscan.name" . }}
  namespace: {{ .Values.global.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "bd-selfscan.name" . }}
rules:
# Core resources for scanning
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
  verbs: ["get", "list", "watch", "patch"]  # patch for annotations
# For Phase 2 automation
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "bd-selfscan.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "bd-selfscan.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "bd-selfscan.name" . }}
  namespace: {{ .Values.global.namespace }}