{{- /* Bool-safe guard: do NOT render when dockerInspector.install=false */ -}}
{{- $install := true -}}
{{- if .Values.dockerInspector -}}
{{-   if hasKey .Values.dockerInspector "install" -}}
{{-     $install = .Values.dockerInspector.install -}}
{{-   end -}}
{{- end -}}
{{- if $install }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-imageinspector-ubuntu
  namespace: {{ .Values.target.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: bd-imageinspector-ubuntu
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ default 1 .Values.dockerInspector.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: bd-imageinspector-ubuntu
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bd-imageinspector-ubuntu
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "selfscan.sa" . }}
      containers:
        - name: ubuntu
          image: {{ default "blackducksoftware/blackduck-imageinspector-ubuntu:6.2.1" .Values.dockerInspector.image | quote }}
          imagePullPolicy: IfNotPresent
          env:
            - name: HTTP_PORT
              value: "9002"
            - name: INSPECTOR_PLATFORM
              value: "UBUNTU"
          ports:
            - containerPort: 9002
              name: http
          volumeMounts:
            - name: shared
              mountPath: /opt/blackduck/blackduck-imageinspector/shared
          # Add resource limits for better pod scheduling
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "2Gi"
              cpu: "1"
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: {{ default "bd-imageinspector-shared" .Values.dockerInspector.sharedPvcName }}
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: bd-imageinspector-ubuntu
  namespace: {{ .Values.target.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: bd-imageinspector-ubuntu
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: bd-imageinspector-ubuntu
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 9002
      targetPort: 9002
      protocol: TCP

{{- end }}
