{{- /* Minimal helper for shared PVC only. No Deployments/Services here. */ -}}
{{- $ns := default .Release.Namespace .Values.target.namespace -}}
{{- $create := default false .Values.dockerInspector.createSharedPvc -}}
{{- $pvcName := default "bd-imageinspector-shared" .Values.dockerInspector.sharedPvcName -}}

{{- if $create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $pvcName }}
  namespace: {{ $ns }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
{{- end }}
